// =============================================================================
// POKÉMATHS — TOPIC ENGINE
// =============================================================================
// 37 curriculum-aligned maths topics, each with its own question generator.
// Topic *labels* follow a standard UK KS1/KS2 progression; every question here
// is generated by our own code.
//
// A Question's `answer` is always numeric (supports decimals and negatives) so
// it can be entered on the game keypad. Where an answer is a fraction we ask
// for its value ("1/2 of 8 = ?") rather than fraction notation.
// =============================================================================

export interface Question {
  text: string; // e.g. "3 + 4 = ?"
  answer: number; // numeric answer (may be a decimal or negative)
  hint: string; // shown as a nudge
  /** How close a typed answer must be to count (for decimal rounding). Default 0. */
  tolerance?: number;
}

export type TopicId =
  | 'counting'
  | 'adding'
  | 'subtracting'
  | 'more_adding'
  | 'more_subtracting'
  | 'tables_1_2_5_10'
  | 'adding_bigger'
  | 'tables_3_6_9'
  | 'place_value'
  | 'tables_4_8'
  | 'subtracting_bigger'
  | 'tens_hundreds_thousands'
  | 'table_7'
  | 'dividing_to_10'
  | 'dividing_remainders'
  | 'negatives'
  | 'mult_div_powers10'
  | 'tables_11_12'
  | 'fractions'
  | 'decimals'
  | 'long_mult_start'
  | 'long_div_start'
  | 'percentages_start'
  | 'more_decimals'
  | 'more_fractions'
  | 'percentages_money'
  | 'squares_roots_cubes'
  | 'long_mult_pro'
  | 'long_div_pro'
  | 'sequences_patterns'
  | 'ratio_proportion'
  | 'estimating'
  | 'number_skills'
  | 'fdp'
  | 'ratio_proportion_2'
  | 'algebra_start'
  | 'sequences';

export interface Topic {
  id: TopicId;
  name: string; // display label
  generate: () => Question;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------
/** random integer in [min, max] inclusive */
const r = (min: number, max: number): number =>
  Math.floor(Math.random() * (max - min + 1)) + min;

/** pick a random element */
const pick = <T,>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];

/** round to n decimal places, avoiding float noise */
const round = (x: number, n = 2): number => {
  const f = 10 ** n;
  return Math.round(x * f) / f;
};

// ---------------------------------------------------------------------------
// generators — keyed by TopicId
// ---------------------------------------------------------------------------
const GENERATORS: Record<TopicId, () => Question> = {
  // 1. Counting and number lines — "what comes next / fill the gap"
  counting: () => {
    const start = r(0, 15);
    const step = pick([1, 2, 2, 5, 10]);
    const seq = [start, start + step, start + step * 2];
    return {
      text: `${seq[0]}, ${seq[1]}, ${seq[2]}, ?`,
      answer: start + step * 3,
      hint: `Counting up in ${step}s`,
    };
  },

  // 2. Adding up (to ~10)
  adding: () => {
    const a = r(1, 10);
    const b = r(1, 10);
    return { text: `${a} + ${b} = ?`, answer: a + b, hint: `Count on ${b} from ${a}` };
  },

  // 3. Subtracting (within 10)
  subtracting: () => {
    const a = r(2, 10);
    const b = r(1, a);
    return { text: `${a} − ${b} = ?`, answer: a - b, hint: `Count back ${b} from ${a}` };
  },

  // 4. More adding up (to ~20, three numbers sometimes)
  more_adding: () => {
    if (Math.random() < 0.5) {
      const a = r(5, 20);
      const b = r(5, 20);
      return { text: `${a} + ${b} = ?`, answer: a + b, hint: `Make 10 first, then add the rest` };
    }
    const a = r(1, 9);
    const b = r(1, 9);
    const c = r(1, 9);
    return { text: `${a} + ${b} + ${c} = ?`, answer: a + b + c, hint: `Add two, then the third` };
  },

  // 5. More subtracting (within 20)
  more_subtracting: () => {
    const a = r(10, 20);
    const b = r(1, a);
    return { text: `${a} − ${b} = ?`, answer: a - b, hint: `Count back from ${a}` };
  },

  // 6. The 1, 2, 5 and 10 times tables
  tables_1_2_5_10: () => {
    const m = pick([1, 2, 5, 10]);
    const n = r(1, 12);
    return { text: `${m} × ${n} = ?`, answer: m * n, hint: `${m} lots of ${n}` };
  },

  // 7. Adding bigger numbers (2–3 digit)
  adding_bigger: () => {
    const a = r(20, 200);
    const b = r(20, 200);
    return { text: `${a} + ${b} = ?`, answer: a + b, hint: `Add the tens, then the units` };
  },

  // 8. The 3, 6 and 9 times tables
  tables_3_6_9: () => {
    const m = pick([3, 6, 9]);
    const n = r(1, 12);
    return { text: `${m} × ${n} = ?`, answer: m * n, hint: `${m} times table` };
  },

  // 9. Units, tens, hundreds and thousands — place value
  place_value: () => {
    const num = r(1000, 9999);
    const places = [
      { name: 'thousands', div: 1000 },
      { name: 'hundreds', div: 100 },
      { name: 'tens', div: 10 },
      { name: 'units', div: 1 },
    ];
    const p = pick(places);
    const digit = Math.floor(num / p.div) % 10;
    return {
      text: `In ${num}, which digit is in the ${p.name}?`,
      answer: digit,
      hint: `Look at the ${p.name} column`,
    };
  },

  // 10. The 4 and 8 times tables
  tables_4_8: () => {
    const m = pick([4, 8]);
    const n = r(1, 12);
    return { text: `${m} × ${n} = ?`, answer: m * n, hint: `${m} times table` };
  },

  // 11. Subtracting bigger numbers
  subtracting_bigger: () => {
    const a = r(100, 900);
    const b = r(20, a);
    return { text: `${a} − ${b} = ?`, answer: a - b, hint: `Take away in steps` };
  },

  // 12. Tens, hundreds and thousands (rounding)
  tens_hundreds_thousands: () => {
    const to = pick([10, 100]);
    const num = to === 10 ? r(11, 99) : r(120, 980);
    return {
      text: `Round ${num} to the nearest ${to}`,
      answer: Math.round(num / to) * to,
      hint: `Is it closer to the lower or higher ${to}?`,
    };
  },

  // 13. The 7 times table
  table_7: () => {
    const n = r(1, 12);
    return { text: `7 × ${n} = ?`, answer: 7 * n, hint: `7 times table` };
  },

  // 14. Dividing by numbers up to 10
  dividing_to_10: () => {
    const b = r(2, 10);
    const q = r(1, 12);
    return { text: `${b * q} ÷ ${b} = ?`, answer: q, hint: `How many ${b}s make ${b * q}?` };
  },

  // 15. Dividing with remainders — "what is the remainder?"
  dividing_remainders: () => {
    const b = r(3, 9);
    const q = r(2, 9);
    const rem = r(1, b - 1);
    const a = b * q + rem;
    return {
      text: `${a} ÷ ${b} — what is the remainder?`,
      answer: rem,
      hint: `${b} × ${q} = ${b * q}, what's left over?`,
    };
  },

  // 16. Numbers less than zero
  negatives: () => {
    const a = r(1, 9);
    const b = r(a + 1, a + 10);
    return { text: `${a} − ${b} = ?`, answer: a - b, hint: `Go below zero on the number line` };
  },

  // 17. Multiplying and dividing by 10, 100, 1000
  mult_div_powers10: () => {
    const p = pick([10, 100, 1000]);
    if (Math.random() < 0.5) {
      const n = r(2, 99);
      return { text: `${n} × ${p} = ?`, answer: n * p, hint: `Shift digits left` };
    }
    const q = r(2, 99);
    return { text: `${q * p} ÷ ${p} = ?`, answer: q, hint: `Shift digits right` };
  },

  // 18. The 11 and 12 times tables
  tables_11_12: () => {
    const m = pick([11, 12]);
    const n = r(1, 12);
    return { text: `${m} × ${n} = ?`, answer: m * n, hint: `${m} times table` };
  },

  // 19. Lovely fractions — fraction of an amount
  fractions: () => {
    const den = pick([2, 3, 4, 5]);
    const whole = den * r(2, 8);
    return {
      text: `1/${den} of ${whole} = ?`,
      answer: whole / den,
      hint: `Split ${whole} into ${den} equal parts`,
    };
  },

  // 20. Lovely decimals — add/subtract 1dp
  decimals: () => {
    const a = round(r(1, 90) / 10, 1);
    const b = round(r(1, 90) / 10, 1);
    if (Math.random() < 0.5) {
      return { text: `${a} + ${b} = ?`, answer: round(a + b, 1), hint: `Line up the decimal points`, tolerance: 0.001 };
    }
    const hi = Math.max(a, b);
    const lo = Math.min(a, b);
    return { text: `${hi} − ${lo} = ?`, answer: round(hi - lo, 1), hint: `Line up the decimal points`, tolerance: 0.001 };
  },

  // 21. Starting long multiplication (2-digit × 1-digit)
  long_mult_start: () => {
    const a = r(11, 39);
    const b = r(3, 9);
    return { text: `${a} × ${b} = ?`, answer: a * b, hint: `Multiply units, then tens` };
  },

  // 22. Starting long division (÷ 1-digit, no remainder)
  long_div_start: () => {
    const b = r(3, 9);
    const q = r(11, 40);
    return { text: `${b * q} ÷ ${b} = ?`, answer: q, hint: `How many ${b}s fit?` };
  },

  // 23. Starting percentages — 10% / 50% / 25% of an amount
  percentages_start: () => {
    const p = pick([10, 25, 50]);
    const whole = pick([20, 40, 60, 80, 100, 200]);
    return {
      text: `${p}% of ${whole} = ?`,
      answer: (whole * p) / 100,
      hint: p === 50 ? 'Half it' : p === 25 ? 'Quarter it' : 'Divide by 10',
    };
  },

  // 24. More decimals — × 10 / ÷ 10, 2dp
  more_decimals: () => {
    const a = round(r(10, 990) / 100, 2);
    if (Math.random() < 0.5) {
      return { text: `${a} × 10 = ?`, answer: round(a * 10, 1), hint: `Digits shift one place left`, tolerance: 0.001 };
    }
    return { text: `${a} × 100 = ?`, answer: round(a * 100, 0), hint: `Digits shift two places left`, tolerance: 0.001 };
  },

  // 25. More fractions — non-unit fraction of an amount
  more_fractions: () => {
    const den = pick([3, 4, 5, 6, 8]);
    const num = r(2, den - 1);
    const whole = den * r(2, 6);
    return {
      text: `${num}/${den} of ${whole} = ?`,
      answer: (whole / den) * num,
      hint: `Find 1/${den} first, then ×${num}`,
    };
  },

  // 26. Percentages and money
  percentages_money: () => {
    const p = pick([10, 20, 25, 50]);
    const pounds = pick([20, 40, 50, 80, 100]);
    return {
      text: `${p}% of £${pounds} = £?`,
      answer: (pounds * p) / 100,
      hint: `${p}% means ${p} out of 100`,
    };
  },

  // 27. Squares, square roots and cubes
  squares_roots_cubes: () => {
    const kind = pick(['square', 'root', 'cube']);
    if (kind === 'square') {
      const n = r(2, 12);
      return { text: `${n}² = ?`, answer: n * n, hint: `${n} × ${n}` };
    }
    if (kind === 'cube') {
      const n = r(2, 6);
      return { text: `${n}³ = ?`, answer: n ** 3, hint: `${n} × ${n} × ${n}` };
    }
    const n = r(2, 12);
    return { text: `√${n * n} = ?`, answer: n, hint: `What times itself makes ${n * n}?` };
  },

  // 28. Being brilliant at long multiplication (2-digit × 2-digit)
  long_mult_pro: () => {
    const a = r(12, 40);
    const b = r(12, 25);
    return { text: `${a} × ${b} = ?`, answer: a * b, hint: `Split into tens and units` };
  },

  // 29. Being brilliant at long division (÷ 1-digit with remainder as quotient)
  long_div_pro: () => {
    const b = r(3, 9);
    const q = r(20, 90);
    return { text: `${b * q} ÷ ${b} = ?`, answer: q, hint: `Divide each part in turn` };
  },

  // 30. Number patterns and sequences — next term
  sequences_patterns: () => {
    const start = r(1, 9);
    const step = r(2, 9);
    const seq = [start, start + step, start + step * 2, start + step * 3];
    return {
      text: `${seq[0]}, ${seq[1]}, ${seq[2]}, ${seq[3]}, ?`,
      answer: start + step * 4,
      hint: `The step is +${step}`,
    };
  },

  // 31. Ratio & Proportion — scale up a ratio
  ratio_proportion: () => {
    const a = r(1, 5);
    const b = r(2, 6);
    const k = r(2, 6);
    return {
      text: `${a} : ${b} = ${a * k} : ?`,
      answer: b * k,
      hint: `Both sides ×${k}`,
    };
  },

  // 32. Estimating and checking — round then add
  estimating: () => {
    const a = r(11, 99);
    const b = r(11, 99);
    const est = Math.round(a / 10) * 10 + Math.round(b / 10) * 10;
    return {
      text: `Estimate ${a} + ${b} (round to nearest 10)`,
      answer: est,
      hint: `Round each number first`,
    };
  },

  // 33. Number skills — order of operations (× before +)
  number_skills: () => {
    const a = r(2, 9);
    const b = r(2, 9);
    const c = r(2, 9);
    return { text: `${a} + ${b} × ${c} = ?`, answer: a + b * c, hint: `Do × before +` };
  },

  // 34. Fractions, decimals and percentages — convert
  fdp: () => {
    const map = [
      { f: '1/2', v: 0.5 },
      { f: '1/4', v: 0.25 },
      { f: '3/4', v: 0.75 },
      { f: '1/5', v: 0.2 },
      { f: '1/10', v: 0.1 },
    ];
    const m = pick(map);
    return {
      text: `${m.f} as a decimal = ?`,
      answer: m.v,
      hint: `Divide top by bottom`,
      tolerance: 0.001,
    };
  },

  // 35. Ratio and Proportion II — sharing in a ratio
  ratio_proportion_2: () => {
    const a = r(1, 4);
    const b = r(1, 4);
    const part = r(3, 8);
    const total = (a + b) * part;
    return {
      text: `Share ${total} in ratio ${a}:${b} — the ${a}-part = ?`,
      answer: a * part,
      hint: `${a + b} parts make ${total}, so 1 part = ${part}`,
    };
  },

  // 36. Starting Algebra — solve for x
  algebra_start: () => {
    const x = r(2, 12);
    const b = r(1, 9);
    const kind = pick(['add', 'mult']);
    if (kind === 'add') {
      return { text: `x + ${b} = ${x + b}, x = ?`, answer: x, hint: `Take ${b} off both sides` };
    }
    const m = r(2, 6);
    return { text: `${m}x = ${m * x}, x = ?`, answer: x, hint: `Divide both sides by ${m}` };
  },

  // 37. Sequences — find the nth-ish next term with mixed steps
  sequences: () => {
    const start = r(1, 5);
    const step = r(3, 12);
    const n = 5;
    const terms = Array.from({ length: n }, (_, i) => start + step * i);
    return {
      text: `${terms.join(', ')}, ?`,
      answer: start + step * n,
      hint: `Rule: start ${start}, add ${step} each time`,
    };
  },
};

// ---------------------------------------------------------------------------
// display labels (curriculum topic names)
// ---------------------------------------------------------------------------
const TOPIC_NAMES: Record<TopicId, string> = {
  counting: 'Counting & number lines',
  adding: 'Adding up',
  subtracting: 'Subtracting',
  more_adding: 'More adding up',
  more_subtracting: 'More subtracting',
  tables_1_2_5_10: 'The 1, 2, 5 & 10 times tables',
  adding_bigger: 'Adding bigger numbers',
  tables_3_6_9: 'The 3, 6 & 9 times tables',
  place_value: 'Units, tens, hundreds & thousands',
  tables_4_8: 'The 4 & 8 times tables',
  subtracting_bigger: 'Subtracting bigger numbers',
  tens_hundreds_thousands: 'Rounding to 10s, 100s & 1000s',
  table_7: 'The 7 times table',
  dividing_to_10: 'Dividing by numbers up to 10',
  dividing_remainders: 'Dividing with remainders',
  negatives: 'Numbers less than zero',
  mult_div_powers10: 'Multiply & divide by 10, 100, 1000',
  tables_11_12: 'The 11 & 12 times tables',
  fractions: 'Lovely fractions',
  decimals: 'Lovely decimals',
  long_mult_start: 'Starting long multiplication',
  long_div_start: 'Starting long division',
  percentages_start: 'Starting percentages',
  more_decimals: 'More decimals',
  more_fractions: 'More fractions',
  percentages_money: 'Percentages & money',
  squares_roots_cubes: 'Squares, square roots & cubes',
  long_mult_pro: 'Brilliant long multiplication',
  long_div_pro: 'Brilliant long division',
  sequences_patterns: 'Number patterns & sequences',
  ratio_proportion: 'Ratio & proportion',
  estimating: 'Estimating & checking',
  number_skills: 'Number skills',
  fdp: 'Fractions, decimals & percentages',
  ratio_proportion_2: 'Ratio & proportion II',
  algebra_start: 'Starting algebra',
  sequences: 'Sequences',
};

export const TOPICS: Record<TopicId, Topic> = Object.fromEntries(
  (Object.keys(GENERATORS) as TopicId[]).map((id) => [
    id,
    { id, name: TOPIC_NAMES[id], generate: GENERATORS[id] },
  ]),
) as Record<TopicId, Topic>;

export function getTopic(id: TopicId): Topic {
  return TOPICS[id];
}

/** Check a typed answer against a question, honouring per-question tolerance. */
export function isAnswerCorrect(q: Question, typed: number): boolean {
  const tol = q.tolerance ?? 0;
  return Math.abs(typed - q.answer) <= tol;
}
